services:
  - type: web
    name: hedera-gamers-vault-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_MY_ACCOUNT_ID
        sync: false
      - key: VITE_MY_PRIVATE_KEY
        sync: false
      - key: VITE_PINATA_JWT
        sync: false
      - key: VITE_PINATA_GATEWAY
        sync: false
      - key: VITE_ADMIN_ACCOUNTS
        sync: false
      - key: FRONTEND_URL
        sync: false
