name: Deploy to GitHub Pages

on:
  push:
    branches: [ gamersnft ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          VITE_MY_ACCOUNT_ID: ${{ secrets.VITE_MY_ACCOUNT_ID }}
          VITE_MY_PRIVATE_KEY: ${{ secrets.VITE_MY_PRIVATE_KEY }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_HEDERA_NETWORK: testnet
          VITE_PINATA_JWT: ${{ secrets.VITE_PINATA_JWT }}
          VITE_PINATA_GATEWAY: ${{ secrets.VITE_PINATA_GATEWAY }}
          VITE_ADMIN_ACCOUNTS: ${{ secrets.VITE_ADMIN_ACCOUNTS }}
          VITE_BACKEND_URL: https://gamersnft-backend.onrender.com
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
